version: '3.8'
services:
  redis: 
    image: redis:7.0.11-alpine
  django:
    container_name: django
    build: 
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=DFDFDFDK54K54LKLKGLFLF
      - ALLOWED_HOSTS=127.0.0.1 
    depends_on:
      - redis 
  celery:
    container_name: celery
    build: 
      context: ./
    command: celery --app=config worker -l INFO -Q queue1
    volumes:
      - /usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=DFDFDFDK54K54LKLKGLFLF
      - ALLOWED_HOSTS=127.0.0.1 
    depends_on:
      - redis 
      - django
  celery2:
    container_name: celery2
    build: 
      context: ./celeryworker
      dockerfile: Dockerfile 
    command: celery -A celerytasks worker -l INFO -Q queue1
    volumes:
      - ./celeryworker:/usr/src/app/
    depends_on:
      - redis 
      - django



